version: '3.9'
services:
  service-01:
    build:
      context: .
      dockerfile: ./Dockerfile-01
    container_name: service-01
    tty: true
    stdin_open: true
    networks:
      - app-network
    command: /usr/bin/bash

  service-02:
    build:
      context: .
      dockerfile: ./Dockerfile-02
    container_name: service-02
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    shm_size: '30g'
    networks:
      - app-network
    command: /usr/bin/bash

networks:
  app-network:
    driver: bridge
